//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileServerSystemClient.UserManagementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementService.IUserController")]
    public interface IUserController {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/RegisterNewUser", ReplyAction="http://tempuri.org/IUserController/RegisterNewUserResponse")]
        string RegisterNewUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/RegisterNewUser", ReplyAction="http://tempuri.org/IUserController/RegisterNewUserResponse")]
        System.Threading.Tasks.Task<string> RegisterNewUserAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/UserLogin", ReplyAction="http://tempuri.org/IUserController/UserLoginResponse")]
        string UserLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/UserLogin", ReplyAction="http://tempuri.org/IUserController/UserLoginResponse")]
        System.Threading.Tasks.Task<string> UserLoginAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/UserLogOff", ReplyAction="http://tempuri.org/IUserController/UserLogOffResponse")]
        string UserLogOff(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserController/UserLogOff", ReplyAction="http://tempuri.org/IUserController/UserLogOffResponse")]
        System.Threading.Tasks.Task<string> UserLogOffAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserControllerChannel : FileServerSystemClient.UserManagementService.IUserController, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserControllerClient : System.ServiceModel.ClientBase<FileServerSystemClient.UserManagementService.IUserController>, FileServerSystemClient.UserManagementService.IUserController {
        
        public UserControllerClient() {
        }
        
        public UserControllerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserControllerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RegisterNewUser(string userName, string password) {
            return base.Channel.RegisterNewUser(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> RegisterNewUserAsync(string userName, string password) {
            return base.Channel.RegisterNewUserAsync(userName, password);
        }
        
        public string UserLogin(string userName, string password) {
            return base.Channel.UserLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<string> UserLoginAsync(string userName, string password) {
            return base.Channel.UserLoginAsync(userName, password);
        }
        
        public string UserLogOff(string userName) {
            return base.Channel.UserLogOff(userName);
        }
        
        public System.Threading.Tasks.Task<string> UserLogOffAsync(string userName) {
            return base.Channel.UserLogOffAsync(userName);
        }
    }
}
