CREATE TABLE [USER]
(
	Login NVARCHAR(20) PRIMARY KEY,
	Password NVARCHAR(20) NOT NULL


)

CREATE TABLE TOKEN
(
	Token NVARCHAR(20),
	Login NVARCHAR(20),
	Is_Active BIT NOT NULL,

	CONSTRAINT PK_TOKEN_KEYS PRIMARY KEY NONCLUSTERED (Token, Login)
)

CREATE TABLE [FILE]
(
	Login NVARCHAR(20) FOREIGN KEY(Login) REFERENCES [USER],
	File_Length NVARCHAR(20) NOT NULL,
	File_Data NVARCHAR(20) NOT NULL,
	[File_Name] NVARCHAR(20) NOT NULL,
	File_Extension NVARCHAR(20) NOT NULL

)