CREATE TABLE [USER]
(
	Login NVARCHAR(20) PRIMARY KEY,
	Password NVARCHAR(20) NOT NULL


)

CREATE TABLE TOKEN
(
	Token NVARCHAR(20) PRIMARY KEY NONCLUSTERED (Token),
	Login NVARCHAR(20) FOREIGN KEY(Login) REFERENCES [USER],
	Is_Active BIT NOT NULL

)

CREATE TABLE [FILE]
(
	Login NVARCHAR(20) FOREIGN KEY(Login) REFERENCES [USER],
	File_Length NVARCHAR(20) NOT NULL,
	File_Data NVARCHAR(20) NOT NULL,
	[File_Name] NVARCHAR(20) NOT NULL,
	File_Extension NVARCHAR(20) NOT NULL

)